# Generated by Django 5.1.4 on 2024-12-28 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_followers"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="followerss", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="followingg", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
